all:
  children:
    azure:
      hosts:
        azure_lab_vm:
          ansible_host: 20.11.188.70
          ansible_user: lab.admin
          ansible_ssh_private_key_file: ~/.ssh/azure-lab-private-key
          ansible_become: true
          ansible_become_method: sudo
          ansible_become_password: "Windows7@Lab"

    homelab:
      hosts:
        syd_vm01:
          ansible_host: 100.69.145.33
          ansible_user: lab.admin
          ansible_ssh_private_key_file: ~/.ssh/azure-lab-private-key
          ansible_become: true
          ansible_become_method: sudo
          ansible_become_password: "Windows7"

    gcp:
      hosts:
        localhost:
          ansible_connection: local