all:
  children:
    azure:
      hosts:
        azure_lab_vm:
          ansible_host: 20.92.25.141
          ansible_user: ops
          ansible_ssh_private_key_file: ~/.ssh/azure-lab-private-key
          ansible_become: true
          ansible_become_method: sudo

      children:
        k3s_cluster:
          vars:
            ansible_user: ops
            ansible_ssh_private_key_file: ~/.ssh/azure-lab-private-key
            ansible_become: true
            ansible_become_method: sudo
            # SSH ProxyJump: Tunnels traffic through the public Jumpbox to reach private IPs
            ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q -i ~/.ssh/azure-lab-private-key -o StrictHostKeyChecking=no ops@20.92.25.141"'
          children:
            k3s_master:
              hosts:
                k3s-master-node:
                  ansible_host: 10.0.1.5
            k3s_worker:
              hosts:
                k3s-worker-node:
                  ansible_host: 10.0.1.6

    homelab:
      hosts:
        syd_vm01:
          ansible_host: 100.69.145.33
          ansible_user: lab.admin
          ansible_ssh_private_key_file: ~/.ssh/azure-lab-private-key
          ansible_become: true
          ansible_become_method: sudo
          ansible_become_password: "Windows7"

    gcp:
      hosts:
        localhost:
          ansible_connection: local