all:
  children:
    azure:
      hosts:
        azure_lab_vm:
          ansible_host: 20.92.25.141  # Direct IP bypasses public DNS caching
          # 1. Switch to your newly created automation user
          ansible_user: ops
          ansible_ssh_private_key_file: ~/.ssh/azure-lab-private-key
          ansible_become: true
          ansible_become_method: sudo
          # 2. No ansible_become_password required anymore because of NOPASSWD:ALL!

    homelab:
      hosts:
        syd_vm01:
          ansible_host: 100.95.115.103
          ansible_user: lab.admin
          ansible_ssh_private_key_file: ~/.ssh/azure-lab-private-key
          ansible_become: true
          ansible_become_method: sudo
          ansible_become_password: "YourLocalPasswordHere"

    gcp:
      hosts:
        localhost:
          ansible_connection: local
